apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "genoa-webhook.fullname" $ }}
rules:
  - apiGroups:
      - coveros.apps.com
    resources:
      - releases
      - releases/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
      - get
      - list