{{ $root := . }}
{{- with .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genoa-webhook.fullname" $ }}
  namespace: {{ $root.Release.Namespace }}
  {{- if .labels }}
  labels:
  {{ toYaml .labels | indent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
  {{ toYaml .annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "genoa-webhook.selectorLabels" $ | nindent 6 }}
  replicas: {{ .replicaCount | default 1 }}
  template:
    metadata:
      labels: {{- include "genoa-webhook.selectorLabels" $ | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $root | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/notification-secret.yaml") $root | sha256sum }}
        {{- if .podAnnotations }}
        {{ toYaml .podAnnotations | indent 8 }}
        {{- end }}
    spec:
      {{- if .nodeSelector }}
      nodeSelector:
      {{ toYaml .nodeSelector | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genoa-webhook.serviceAccountName" $ }}
      {{- if .volumes }}
      {{ toYaml .volumes | indent 6 }}
      {{- end }}
      {{- if .imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .imagePullSecrets | indent 6 }}
      {{- end }}
      {{- if .initContainers }}
      initContainers:
      {{- toYaml .initContainers | indent 6 }}
      {{- end }}
      containers:
        - name: {{ include "genoa-webhook.fullname" $ }}
          command:
            - /genoa-webhook
          image: {{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- if .volumeMounts }}
          {{ toYaml .volumeMounts | indent 8 }}
          {{- end }}
          {{- if .resources }}
          resources:
          {{ toYaml .resources | indent 10 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "genoa-webhook.fullname" $ }}
            {{- if $root.Values.config.notification.enabled }}
            - secretRef:
                name: notification-secret
            {{- end }}
          {{- if .envVars }}
          env:
      {{ toYaml .envVars | indent 8 }}
  {{- end }}
  {{- end }}